services:
  # Gluetun VPN service (optional)
  vpn:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN  # Required for VPN networking
    devices:
      - /dev/net/tun:/dev/net/tun  # Required for VPN tunneling
    restart: unless-stopped
    environment:
      # VPN provider configuration
      - VPN_SERVICE_PROVIDER=${VPN_PROVIDER:-private internet access}
      - VPN_TYPE=${VPN_TYPE:-openvpn}
      # Provider-specific credentials
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      # Optional VPN settings
      # - SERVER_COUNTRIES=${VPN_COUNTRY:-US}
      - SERVER_REGIONS=${VPN_REGION:-}
      - SERVER_CITIES=${VPN_CITY:-}
      # Health check settings
      - HEALTH_TARGET_ADDRESS=${HEALTH_TARGET_ADDRESS:-1.1.1.1}
      - DOT=off
      - DNS_ADDRESS=9.9.9.9
    # Expose the WebSocket port for the grabsite dashboard
    ports:
      - "29000:29000"
    # Create a named network for containers to join
    networks:
      - vpn_network
    profiles:
      - vpn  # Only used when VPN is enabled

  # Custom grab-site container (with VPN)
  grabsite:
    platform: linux/amd64
    build:
      context: ./grabsite
      dockerfile: Dockerfile
    depends_on:
      - vpn
    network_mode: service:vpn  # Routes all traffic through VPN
    volumes:
      - ./output:/home/grabsite/output  # data/output directory
    working_dir: /home/grabsite/output
    # Start the dashboard server by default
    command: gs-server --bind 0.0.0.0
    profiles:
      - vpn  # Only used when VPN is enabled

  # Custom grab-site container (no VPN)
  grabsite-direct:
    platform: linux/amd64
    build:
      context: ./grabsite
      dockerfile: Dockerfile
    # Expose dashboard port directly
    ports:
      - "29000:29000"
    volumes:
      - ./output:/home/grabsite/output  # data/output directory
    working_dir: /home/grabsite/output
    # Start the dashboard server by default
    command: gs-server --bind 0.0.0.0
    networks:
      - default
    profiles:
      - default  # Used by default if no profile specified

networks:
  vpn_network:
    driver: bridge
  default:
