services:
  # Network utilities container (with VPN)
  netutils:
    image: nicolaka/netshoot:latest
    depends_on:
      - vpn
    network_mode: service:vpn  # Route through VPN
    volumes:
      - ./utils:/utils  # Optional shared volume for scripts or results
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate a pseudo-TTY
    restart: "no"
    profiles:
      - vpn  # Only used with VPN

  # Network utilities container (no VPN)
  netutils-direct:
    image: nicolaka/netshoot:latest
    volumes:
      - ./utils:/utils  # Optional shared volume for scripts or results
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate a pseudo-TTY
    restart: "no"
    profiles:
      - default  # Used by default if no profile specified
    networks:
      - default